name: "BCIOT Org2 Client"
x-type: "hlfv1"
description: "Client Definition for Org2"
version: "1.0"
client:
  organization: Org2
  credentialStore:
    path: "/tmp/hfc-kvs/org2"
    cryptoStore:
      path: "/tmp/hfc-cvs/org2"
  #connection:
  #  options
  #    grpc.keepalive_time_ms: 120000